% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Taller 2 Regresión},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{Taller 2 Regresión}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(car)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: carData
\end{verbatim}

\begin{verbatim}
## Registered S3 methods overwritten by 'tibble':
##   method     from  
##   format.tbl pillar
##   print.tbl  pillar
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(dplyr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'dplyr'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:car':
## 
##     recode
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     filter, lag
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(rsm)}
\FunctionTok{library}\NormalTok{(leaps)}
\FunctionTok{library}\NormalTok{(olsrr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'olsrr' was built under R version 4.0.5
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'olsrr'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:datasets':
## 
##     rivers
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(knitr)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#LEER DATOS EN archivo asignado a su grupo, así:}
\NormalTok{datos}\OtherTok{=}\FunctionTok{read.table}\NormalTok{(}\StringTok{"APC1modifm3.csv"}\NormalTok{,}\AttributeTok{header=}\NormalTok{T,}\AttributeTok{sep=}\StringTok{";"}\NormalTok{,}\AttributeTok{dec=}\StringTok{","}\NormalTok{,}
\AttributeTok{colClasses=}\FunctionTok{c}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\StringTok{"numeric"}\NormalTok{,}\DecValTok{7}\NormalTok{),}\StringTok{"factor"}\NormalTok{,}\FunctionTok{rep}\NormalTok{(}\StringTok{"numeric"}\NormalTok{,}\DecValTok{3}\NormalTok{),}\StringTok{"factor"}\NormalTok{))}
\CommentTok{\#CONSULTA DE NOMBRE DE VARIABLES EN OBJETO datos}
 
\NormalTok{regresoras }\OtherTok{\textless{}{-}} \FunctionTok{names}\NormalTok{(datos)[}\FunctionTok{names}\NormalTok{(datos) }\SpecialCharTok{!=} \FunctionTok{c}\NormalTok{(}\StringTok{"ID"}\NormalTok{, }\StringTok{"AEM"}\NormalTok{, }\StringTok{"REGION"}\NormalTok{)] }
\NormalTok{numericas }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(regresoras)}
\NormalTok{regresoras }\OtherTok{\textless{}{-}} \FunctionTok{paste}\NormalTok{(regresoras[}\DecValTok{2}\SpecialCharTok{:}\FunctionTok{length}\NormalTok{(regresoras)], }\AttributeTok{collapse =}\StringTok{" +"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{ajuste-de-modelo-de-regresiuxf3n-lineal-muxfaltiple}{%
\subsection{Ajuste de modelo de regresión lineal
múltiple}\label{ajuste-de-modelo-de-regresiuxf3n-lineal-muxfaltiple}}

Se ajusta un modelo de regresión lineal multiple:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rlm\_formula }\OtherTok{=} \FunctionTok{formula}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"DPERM"}\NormalTok{, regresoras), }\AttributeTok{collapse =} \StringTok{" \textasciitilde{} "}\NormalTok{) )}
\NormalTok{(modelo1 }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(rlm\_formula, }\AttributeTok{data=}\NormalTok{ datos))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = rlm_formula, data = datos)
## 
## Coefficients:
## (Intercept)         EDAD         RINF          RRC          RRX       NCAMAS  
##   -0.208467     0.104381     0.335222     0.028706     0.020982    -0.010699  
##         PDP      NENFERM          FSD  
##    0.022364    -0.006026     0.004160
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{coeficientes\_modelo1 }\OtherTok{\textless{}{-}}\NormalTok{ modelo1}\SpecialCharTok{$}\NormalTok{coefficients}
\end{Highlighting}
\end{Shaded}

Se muestra la tabla de parámetros ajustados:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{kable}\NormalTok{(}\FunctionTok{summary}\NormalTok{(modelo1)}\SpecialCharTok{$}\NormalTok{coefficients)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lrrrr@{}}
\toprule
& Estimate & Std. Error & t value &
Pr(\textgreater\textbar t\textbar) \\
\midrule
\endhead
(Intercept) & -0.2084670 & 1.9450831 & -0.1071764 & 0.9149141 \\
EDAD & 0.1043806 & 0.0340139 & 3.0687638 & 0.0029235 \\
RINF & 0.3352223 & 0.1555968 & 2.1544291 & 0.0341775 \\
RRC & 0.0287063 & 0.0177746 & 1.6150188 & 0.1101955 \\
RRX & 0.0209817 & 0.0085074 & 2.4662932 & 0.0157625 \\
NCAMAS & -0.0106992 & 0.0044559 & -2.4011396 & 0.0186350 \\
PDP & 0.0223642 & 0.0048806 & 4.5822850 & 0.0000165 \\
NENFERM & -0.0060256 & 0.0029319 & -2.0552029 & 0.0430819 \\
FSD & 0.0041605 & 0.0195476 & 0.2128384 & 0.8319878 \\
\bottomrule
\end{longtable}

Se observa que se tienen 90 observaciones y k= 8 variables regresoras.
Escribimos la ecuación ajustada:

\(\hat{Y_i}=-0.2084+0.1043X1+0.3352X2+0.0287X3+0.0209X4-0.0106X5+0.0223X6-0.006X7+0.0041X8\)

Calculamos la tabla ANOVA del modelo:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{kable}\NormalTok{(}\FunctionTok{myAnova}\NormalTok{(modelo1))}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}llllll@{}}
\toprule
& Sum\_of\_Squares & DF & Mean\_Square & F\_Value & P\_value \\
\midrule
\endhead
Model & 217.568 & 8 & 27.19606 & 14.6536 & 5.0418e-13 \\
Error & 150.330 & 81 & 1.85592 & & \\
\bottomrule
\end{longtable}

De la tabla anova del modelo se concluye que el modelo es significativo
ya que el valor p de la prueba de significancia de la regresión es menor
a 0.05.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{kable}\NormalTok{(}\FunctionTok{t}\NormalTok{(}\FunctionTok{summary}\NormalTok{(modelo1)[}\FunctionTok{c}\NormalTok{(}\StringTok{"r.squared"}\NormalTok{, }\StringTok{"adj.r.squared"}\NormalTok{)]))}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}ll@{}}
\toprule
r.squared & adj.r.squared \\
\midrule
\endhead
0.591382042345004 & 0.551024713193893 \\
\bottomrule
\end{longtable}

Del resumen del modelo se obtiene que el valor de \(R^2\) es 0.5914, es
decir que un 59.14\% de la variabilidad total de la variable respuesta
es explicada por el modelo. Se opina que este porcentaje de la
variabilidad tan ``bajo'' puede deberse a que alguna de las covariables
no sea significativa o porque directamente no es adecuado suponer que
existe una relación lineal entre la variable respuesta y las covariables
númericas.

\hypertarget{coeficientes-estandarizados}{%
\subsection{Coeficientes
estandarizados:}\label{coeficientes-estandarizados}}

Se calcula un modelo de regresión lineal multiple con las variables
estándarizadas:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{datos\_estandarizados }\OtherTok{\textless{}{-}}\NormalTok{ datos[, }\FunctionTok{c}\NormalTok{(numericas)] }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{scale}\NormalTok{(}\AttributeTok{center =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{scale =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{data.frame}\NormalTok{()}
\NormalTok{modelo\_estandarizado }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(rlm\_formula, }\AttributeTok{data =}\NormalTok{ datos\_estandarizados)}
\end{Highlighting}
\end{Shaded}

Se imprimen los coeficientes del modelo que incluye las variables
estándarizadas:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{kable}\NormalTok{(}\FunctionTok{t}\NormalTok{(modelo\_estandarizado}\SpecialCharTok{$}\NormalTok{coefficients))}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.13}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.11}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.11}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.11}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.11}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.12}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.10}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.12}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 16\tabcolsep) * \real{0.11}}@{}}
\toprule
(Intercept) & EDAD & RINF & RRC & RRX & NCAMAS & PDP & NENFERM & FSD \\
\midrule
\endhead
0 & 0.2354129 & 0.2254678 & 0.1514452 & 0.2074015 & -0.9777531 &
1.680178 & -0.3839389 & 0.0275649 \\
\bottomrule
\end{longtable}

De la tabla se concluye que la covariable que ``más'' aporta al modelo
cuando los datos se encuentran estándarizados es la covariable ``PDP''.

\hypertarget{significancia-individual-de-los-paruxe1metros-del-modelo}{%
\subsection{Significancia individual de los parámetros del
modelo:}\label{significancia-individual-de-los-paruxe1metros-del-modelo}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{kable}\NormalTok{(}\FunctionTok{summary}\NormalTok{(modelo1)}\SpecialCharTok{$}\NormalTok{coefficients)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lrrrr@{}}
\toprule
& Estimate & Std. Error & t value &
Pr(\textgreater\textbar t\textbar) \\
\midrule
\endhead
(Intercept) & -0.2084670 & 1.9450831 & -0.1071764 & 0.9149141 \\
EDAD & 0.1043806 & 0.0340139 & 3.0687638 & 0.0029235 \\
RINF & 0.3352223 & 0.1555968 & 2.1544291 & 0.0341775 \\
RRC & 0.0287063 & 0.0177746 & 1.6150188 & 0.1101955 \\
RRX & 0.0209817 & 0.0085074 & 2.4662932 & 0.0157625 \\
NCAMAS & -0.0106992 & 0.0044559 & -2.4011396 & 0.0186350 \\
PDP & 0.0223642 & 0.0048806 & 4.5822850 & 0.0000165 \\
NENFERM & -0.0060256 & 0.0029319 & -2.0552029 & 0.0430819 \\
FSD & 0.0041605 & 0.0195476 & 0.2128384 & 0.8319878 \\
\bottomrule
\end{longtable}

De la tabla anterior se concluye que los parámetros \(\beta_1\) y
\(\beta_8\) no son significativos.

\hypertarget{sumas-de-cuadrados-de-tipo-1-y-de-tipo-2}{%
\subsection{Sumas de cuadrados de tipo 1 y de tipo
2:}\label{sumas-de-cuadrados-de-tipo-1-y-de-tipo-2}}

\hypertarget{sumas-de-cuadrados-de-tipo-1}{%
\subsubsection{Sumas de cuadrados de tipo
1:}\label{sumas-de-cuadrados-de-tipo-1}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{kable}\NormalTok{(}\FunctionTok{anova}\NormalTok{(modelo1)[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{2}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lrr@{}}
\toprule
& Df & Sum Sq \\
\midrule
\endhead
EDAD & 1 & 13.2851764 \\
RINF & 1 & 116.2244592 \\
RRC & 1 & 1.9362640 \\
RRX & 1 & 8.4433232 \\
NCAMAS & 1 & 31.8519622 \\
PDP & 1 & 37.8732896 \\
NENFERM & 1 & 7.8699352 \\
FSD & 1 & 0.0840737 \\
Residuals & 81 & 150.3298765 \\
\bottomrule
\end{longtable}

\hypertarget{sumas-de-cuadrados-de-tipo-ii}{%
\subsubsection{Sumas de cuadrados de tipo
II:}\label{sumas-de-cuadrados-de-tipo-ii}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{kable}\NormalTok{(}\FunctionTok{Anova}\NormalTok{(modelo1)[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{2}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lrr@{}}
\toprule
& Sum Sq & Df \\
\midrule
\endhead
EDAD & 17.4778182 & 1 \\
RINF & 8.6143936 & 1 \\
RRC & 4.8407814 & 1 \\
RRX & 11.2888497 & 1 \\
NCAMAS & 10.7002791 & 1 \\
PDP & 38.9694681 & 1 \\
NENFERM & 7.8391631 & 1 \\
FSD & 0.0840737 & 1 \\
Residuals & 150.3298765 & 81 \\
\bottomrule
\end{longtable}

\hypertarget{gruxe1fico-de-residuales-estudentizados-vs-valores-ajustados}{%
\subsection{5.Gráfico de residuales estudentizados vs Valores
ajustados}\label{gruxe1fico-de-residuales-estudentizados-vs-valores-ajustados}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{residualPlots}\NormalTok{(modelo1, }\AttributeTok{type =} \StringTok{"rstudent"}\NormalTok{, }\AttributeTok{tests =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{quadratic =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{fit =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Taller2P1_files/figure-latex/unnamed-chunk-13-1.pdf}

\hypertarget{gruxe1fica-de-probabilidad-normal-para-los-residuales-estudentizados.}{%
\subsection{Gráfica de probabilidad normal para los residuales
estudentizados.}\label{gruxe1fica-de-probabilidad-normal-para-los-residuales-estudentizados.}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ols\_plot\_resid\_qq}\NormalTok{(}\AttributeTok{model =}\NormalTok{ modelo1)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Taller2P1_files/figure-latex/unnamed-chunk-14-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#normalidad \textless{}{-} shapiro.test(modelo1$residuals)}
\CommentTok{\#kable(t(normalidad[c("p.value" ,"statistic" )]))}
\end{Highlighting}
\end{Shaded}

Según la gráfica anterior se observa un desajuste al inicio y al final
de la gráfica que permite dudar sobre la hipótesis de normalidad sobre
los errores del modelo.

\hypertarget{diagnuxf3stico-de-la-presencia-de-observaciones-atuxedpicas-de-balanceo-yo-influenciales.}{%
\subsection{Diagnóstico de la presencia de observaciones atípicas, de
balanceo y/o
influenciales.}\label{diagnuxf3stico-de-la-presencia-de-observaciones-atuxedpicas-de-balanceo-yo-influenciales.}}

Se crea una tabla con las medidas de influencia:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{influencias\_modelo1 }\OtherTok{\textless{}{-}} \FunctionTok{influence.measures}\NormalTok{(modelo1)}
\FunctionTok{kable}\NormalTok{(influencias\_modelo1}\SpecialCharTok{$}\NormalTok{infmat)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 24\tabcolsep) * \real{0.08}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 24\tabcolsep) * \real{0.08}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 24\tabcolsep) * \real{0.08}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 24\tabcolsep) * \real{0.08}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 24\tabcolsep) * \real{0.08}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 24\tabcolsep) * \real{0.08}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 24\tabcolsep) * \real{0.08}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 24\tabcolsep) * \real{0.08}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 24\tabcolsep) * \real{0.08}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 24\tabcolsep) * \real{0.08}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 24\tabcolsep) * \real{0.07}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 24\tabcolsep) * \real{0.07}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 24\tabcolsep) * \real{0.07}}@{}}
\toprule
dfb.1\_ & dfb.EDAD & dfb.RINF & dfb.RRC & dfb.RRX & dfb.NCAM & dfb.PDP &
dfb.NENF & dfb.FSD & dffit & cov.r & cook.d & hat \\
\midrule
\endhead
-0.0384926 & 0.0416417 & 0.0056298 & 0.0580826 & -0.0189245 & -0.0132151
& 0.0025334 & 0.0156094 & 0.0021454 & 0.0864320 & 1.1887575 & 0.0008394
& 0.0697547 \\
0.1058555 & -0.0904158 & -0.2100907 & -0.1203075 & 0.1812456 & 0.0849669
& -0.0212226 & 0.0288100 & -0.1209913 & -0.4176669 & 1.0149776 &
0.0192091 & 0.0914650 \\
-0.0803390 & 0.0614015 & 0.0180373 & 0.0688588 & 0.0087966 & -0.0416342
& -0.0000056 & 0.0857141 & 0.0196582 & 0.1594050 & 1.3957971 & 0.0028552
& 0.2075086 \\
-0.0098613 & -0.0007516 & 0.0727714 & -0.0032847 & -0.0071661 &
-0.0329822 & 0.0227075 & 0.0008369 & -0.0013828 & 0.1112104 & 1.1612327
& 0.0013879 & 0.0583390 \\
0.0014183 & -0.0015835 & -0.0012022 & 0.0017922 & 0.0014277 & -0.0005993
& -0.0001135 & 0.0016989 & -0.0004306 & 0.0047295 & 1.1911510 &
0.0000025 & 0.0612030 \\
-0.0626704 & 0.0287024 & 0.0206027 & -0.0120875 & 0.0728819 & 0.0574992
& -0.0790634 & 0.0508757 & -0.0220114 & -0.1495057 & 1.1161819 &
0.0025005 & 0.0473749 \\
-0.0239095 & 0.0375533 & -0.0355708 & 0.0187289 & 0.0551503 & -0.0565745
& 0.0646585 & 0.0445957 & -0.0591477 & 0.1401584 & 1.1027808 & 0.0021968
& 0.0392196 \\
0.0024569 & -0.0309013 & -0.0156283 & -0.0168329 & 0.0527405 &
-0.1141177 & 0.0521031 & 0.1388904 & 0.0608019 & 0.2080097 & 1.1966912 &
0.0048450 & 0.1038608 \\
0.0902519 & 0.0177271 & 0.2902498 & -0.0207575 & -0.3626614 & -0.1687336
& 0.1217437 & 0.1375595 & -0.1363087 & 0.4984391 & 0.8923623 & 0.0270020
& 0.0812880 \\
-0.0790496 & 0.0004485 & 0.0437451 & 0.0143281 & 0.1023078 & -0.0349038
& 0.0653719 & -0.1286656 & 0.1285106 & 0.2857156 & 1.0453853 & 0.0090486
& 0.0639278 \\
0.0265371 & -0.0126785 & 0.0096227 & -0.0098229 & -0.0225461 &
-0.0158721 & 0.0169149 & 0.0197553 & -0.0335019 & -0.0567325 & 1.1876861
& 0.0003619 & 0.0634456 \\
0.0358934 & -0.0024731 & 0.0057067 & -0.0076874 & -0.0710504 & 0.0024062
& -0.0116592 & -0.0115865 & 0.0069284 & 0.1251866 & 1.1175880 &
0.0017549 & 0.0403582 \\
-0.0492364 & 0.1419770 & 0.0174393 & -0.0086445 & -0.1458428 & 0.0692704
& -0.0766195 & -0.0157130 & -0.0536440 & 0.3283120 & 0.9087960 &
0.0117894 & 0.0450370 \\
-0.0035440 & -0.0076299 & 0.0106649 & -0.0134400 & 0.0116748 & 0.0217710
& -0.0105343 & -0.0536252 & 0.0229826 & -0.0650696 & 1.5313864 &
0.0004763 & 0.2706883 \\
0.0292552 & -0.0664964 & 0.1187368 & -0.1449396 & -0.0356258 &
-0.0140823 & -0.0032059 & 0.0237296 & 0.0487307 & -0.2226108 & 1.0507238
& 0.0055066 & 0.0475333 \\
0.0458349 & -0.0378744 & -0.0346108 & -0.0047528 & 0.0295063 &
-0.0113472 & 0.0123813 & -0.0088123 & -0.0047566 & 0.0925715 & 1.1445980
& 0.0009618 & 0.0434677 \\
0.0130832 & -0.0062318 & -0.0066061 & -0.0005286 & -0.0031522 &
0.0257920 & -0.0064243 & -0.0220509 & -0.0290689 & -0.0590952 &
1.1441759 & 0.0003924 & 0.0335980 \\
0.0469764 & -0.0491820 & 0.0974909 & -0.0960483 & -0.0074902 & 0.0108147
& 0.0002223 & 0.0108439 & -0.0716132 & -0.1380232 & 1.2989815 &
0.0021403 & 0.1495245 \\
0.0259514 & -0.0563945 & 0.0294191 & -0.0804552 & 0.0778785 & 0.0427488
& 0.0220464 & -0.1589242 & 0.0289828 & 0.2211627 & 1.0950251 & 0.0054515
& 0.0611362 \\
0.0933825 & -0.1287563 & 0.0077614 & -0.0786149 & 0.0910189 & 0.0110460
& -0.0070653 & -0.0414976 & 0.0341541 & 0.1774628 & 1.2018242 &
0.0035303 & 0.0989829 \\
0.1410255 & -0.0987945 & -0.0066551 & 0.0153055 & -0.0897428 & 0.0232386
& -0.0351391 & 0.0462228 & -0.0661871 & -0.1915796 & 1.4263831 &
0.0041226 & 0.2269364 \\
-1.0554668 & 0.7022585 & 0.5998931 & -0.3475937 & 0.6269032 & -0.5409321
& 0.7018199 & -0.4175396 & 0.3460527 & 1.9386575 & 0.0461483 & 0.2933926
& 0.0962471 \\
-0.0984735 & 0.1479445 & -0.1734543 & 0.2292467 & 0.0331173 & -0.3012805
& 0.6778416 & -0.3740053 & -0.1557559 & 0.9924519 & 1.8486647 &
0.1092701 & 0.4665856 \\
-0.0488203 & 0.0979679 & -0.1423603 & 0.0549254 & -0.0755257 &
-0.0475879 & 0.0246754 & -0.0139667 & 0.1238480 & 0.2762911 & 1.1462796
& 0.0085132 & 0.0981388 \\
-0.0078033 & 0.0007032 & -0.3519338 & 0.7141728 & -0.0278419 & 0.6263768
& -0.5035366 & -0.2313406 & -0.0308203 & 1.0390092 & 1.8114627 &
0.1195778 & 0.4631417 \\
0.1333173 & -0.1477839 & 0.1335674 & -0.1492003 & -0.0442823 & 0.0124267
& 0.0250202 & -0.0198561 & -0.0688725 & -0.2816428 & 0.9572713 &
0.0087288 & 0.0424889 \\
0.0131837 & -0.0105237 & 0.0181662 & -0.0255704 & -0.0067680 &
-0.0138812 & 0.0043501 & 0.0142993 & 0.0008506 & 0.0416863 & 1.1548215 &
0.0001954 & 0.0366008 \\
-0.0028335 & 0.0063384 & 0.0324916 & -0.0493020 & -0.0348503 & 0.0184680
& -0.0171655 & -0.0152015 & 0.0103967 & -0.0850264 & 1.2096973 &
0.0008125 & 0.0837459 \\
-0.0113679 & 0.0610503 & 0.2457186 & 0.1203398 & -0.4100964 & -0.0987417
& 0.1201803 & -0.2702677 & 0.1256884 & -0.6164232 & 1.0849266 &
0.0417523 & 0.1661595 \\
0.0295788 & -0.0493111 & 0.0449540 & -0.0832218 & -0.0770100 &
-0.1361964 & 0.0876497 & -0.0020406 & 0.1989739 & 0.2708336 & 1.1144807
& 0.0081695 & 0.0832855 \\
-0.1003011 & 0.1061739 & -0.1800559 & 0.1080624 & 0.0493757 & 0.0672866
& -0.0450377 & -0.0013929 & 0.0155961 & -0.2405227 & 1.0643581 &
0.0064308 & 0.0566438 \\
0.0239483 & -0.0381453 & -0.0773553 & 0.0527249 & 0.0317064 & -0.2471923
& 0.0676942 & 0.3188200 & 0.0948138 & -0.4524397 & 1.2828134 & 0.0228001
& 0.2031744 \\
0.0309049 & -0.0229360 & -0.0015687 & -0.0053441 & -0.1482371 &
0.1846951 & -0.2090942 & 0.0200762 & 0.0955841 & 0.3729066 & 1.2537283 &
0.0155147 & 0.1723315 \\
0.1169777 & -0.1402601 & 0.1500199 & 0.1342440 & -0.0595445 & 0.0219951
& 0.0013106 & -0.0933584 & -0.0499572 & 0.3680486 & 1.3678717 &
0.0151505 & 0.2243077 \\
-0.0001688 & 0.0001849 & 0.0082645 & -0.0021751 & -0.0073730 & 0.0037821
& -0.0044101 & -0.0053531 & 0.0022216 & -0.0145083 & 1.2237286 &
0.0000237 & 0.0863888 \\
-0.0849350 & 0.0652693 & -0.0762586 & -0.0385920 & 0.2541075 & 0.3099330
& -0.3642124 & 0.0389461 & -0.1382575 & -0.5141167 & 1.2044771 &
0.0293086 & 0.1848698 \\
0.0204699 & -0.0200790 & 0.0245112 & -0.0471918 & 0.0340662 & -0.0171805
& 0.0055774 & 0.0308436 & -0.0317541 & 0.0859488 & 1.1667349 & 0.0008297
& 0.0550780 \\
0.0612395 & -0.0904378 & 0.0264140 & -0.1063022 & 0.0621991 & 0.0105346
& -0.0354429 & 0.0244946 & 0.0409195 & 0.1681602 & 1.1083998 & 0.0031600
& 0.0500273 \\
-0.0695121 & 0.0603994 & -0.0429912 & 0.0521023 & -0.0296887 &
-0.0121393 & 0.0341929 & -0.0280223 & 0.0523299 & -0.1658626 & 1.0572412
& 0.0030642 & 0.0331408 \\
0.3320045 & -0.3901691 & -0.0255484 & -0.1062093 & 0.0613822 & 0.1202810
& -0.1114995 & -0.1478821 & 0.1495173 & 0.4624005 & 1.2441677 &
0.0237812 & 0.1888977 \\
0.0031616 & 0.0030248 & 0.0584838 & 0.0715268 & -0.0469949 & -0.1133309
& -0.0060568 & 0.0884827 & 0.0346550 & -0.4298770 & 1.0746851 &
0.0204218 & 0.1137510 \\
0.0211207 & -0.0199838 & -0.0022637 & 0.0001081 & 0.0120239 & 0.0001600
& 0.0157781 & -0.0139863 & -0.0303966 & -0.0612693 & 1.1338639 &
0.0004216 & 0.0280495 \\
0.0702132 & -0.0640275 & 0.0111633 & -0.0635615 & 0.0091281 & -0.0189479
& 0.0170428 & 0.0440489 & -0.0466471 & -0.1157146 & 1.2056362 &
0.0015037 & 0.0869842 \\
-0.0579082 & 0.0816794 & 0.0214100 & 0.0731754 & -0.0661098 & -0.0117610
& 0.0142641 & 0.0381211 & -0.0642471 & -0.1564309 & 1.1399129 &
0.0027399 & 0.0601647 \\
-0.0647338 & 0.0105669 & -0.0516484 & 0.0034772 & 0.0433547 & 0.1080651
& -0.1223684 & -0.0849227 & 0.1896070 & 0.2632695 & 1.1959360 &
0.0077472 & 0.1177978 \\
0.0275555 & -0.0210257 & 0.0369466 & -0.0280040 & 0.0024833 & -0.0081521
& 0.0033226 & 0.0274041 & -0.0463087 & 0.0703019 & 1.2093315 & 0.0005556
& 0.0810870 \\
0.0444996 & 0.0177341 & -0.0300423 & -0.0043954 & -0.0680503 & 0.0414753
& -0.0268060 & -0.0166361 & -0.0642726 & 0.1700656 & 1.1614139 &
0.0032393 & 0.0749484 \\
-0.0382775 & 0.0079222 & 0.0075023 & -0.0916394 & 0.1156306 & 0.0099972
& -0.0341736 & 0.1105198 & -0.0311493 & 0.2042364 & 1.3047817 &
0.0046801 & 0.1632672 \\
0.0374032 & -0.0467483 & -0.0073393 & -0.0158719 & 0.0191007 & 0.0266227
& -0.0220295 & -0.0053079 & -0.0064745 & -0.0761568 & 1.1258587 &
0.0006509 & 0.0285238 \\
-0.0402089 & 0.0456678 & 0.0175328 & -0.0281783 & -0.0129565 &
-0.0048318 & 0.0039580 & 0.0206058 & -0.0178769 & -0.0868955 & 1.1317336
& 0.0008473 & 0.0348333 \\
0.0438456 & -0.0343512 & -0.0468420 & 0.0821769 & -0.0246284 &
-0.0764879 & 0.0620400 & 0.0981277 & -0.0384842 & -0.2018585 & 1.0652516
& 0.0045357 & 0.0456530 \\
-0.0029334 & 0.0093912 & -0.0082429 & 0.0020675 & -0.0000151 & 0.0019247
& 0.0006199 & 0.0009167 & -0.0104795 & 0.0189497 & 1.3174769 & 0.0000404
& 0.1513787 \\
-0.0545120 & 0.0468986 & 0.0327360 & 0.0378878 & -0.0695499 & 0.0515116
& -0.0609316 & -0.0083157 & 0.0326910 & -0.1518729 & 1.0772846 &
0.0025741 & 0.0344559 \\
-0.0158863 & 0.0191728 & 0.0001294 & 0.0324871 & 0.0155649 & -0.0366080
& 0.0201481 & 0.0298431 & -0.0092842 & 0.1020384 & 1.1076166 & 0.0011663
& 0.0290469 \\
0.6421624 & -0.6371584 & -0.0369117 & -0.2969916 & 0.0901574 & 0.0267936
& 0.0429387 & -0.2630476 & 0.0648500 & 0.7983544 & 0.5788661 & 0.0659959
& 0.0843432 \\
-0.0284227 & 0.0374475 & -0.0661701 & 0.0426569 & 0.0413780 & 0.0803930
& -0.0723737 & -0.0164358 & -0.0391391 & -0.1392104 & 1.1329967 &
0.0021705 & 0.0516360 \\
-0.0267562 & 0.0442042 & 0.0088145 & 0.0481832 & -0.0320257 & 0.0100840
& -0.0110335 & 0.0213497 & -0.0571767 & -0.1180037 & 1.0977800 &
0.0015579 & 0.0305632 \\
0.0111866 & -0.0087271 & -0.0145801 & 0.0078810 & -0.0035433 &
-0.0251690 & 0.0221171 & 0.0059719 & 0.0096287 & -0.0335163 & 1.5531299
& 0.0001264 & 0.2802088 \\
-0.0529143 & 0.0692944 & -0.0076980 & -0.0085412 & 0.0718821 &
-0.0040831 & 0.0154128 & 0.0307204 & -0.0946116 & 0.1597524 & 1.0959047
& 0.0028508 & 0.0428066 \\
-0.3328238 & 0.2870884 & -0.0651160 & 0.0145697 & 0.1170199 & -0.0072072
& -0.0690868 & -0.0210495 & 0.1690624 & -0.4966824 & 0.8597405 &
0.0267242 & 0.0741590 \\
0.0568901 & -0.0397054 & 0.1084650 & 0.0787975 & -0.1609209 & 0.0555187
& -0.0538616 & -0.0466703 & -0.0376042 & -0.2652599 & 0.9969937 &
0.0077745 & 0.0461662 \\
-0.0984058 & 0.0983355 & 0.0042810 & 0.1604606 & -0.1181551 & -0.0814065
& -0.1199827 & 0.2856051 & 0.1011190 & -0.4940348 & 0.9779787 &
0.0267332 & 0.1011611 \\
-0.0224146 & 0.0015600 & 0.0357685 & -0.0223232 & 0.0205585 & 0.0002264
& -0.0011650 & 0.0015918 & 0.0050866 & -0.0662833 & 1.1782329 &
0.0004938 & 0.0584033 \\
-0.0252613 & 0.0230153 & -0.0389732 & 0.0141225 & 0.0444752 & 0.0194854
& -0.0187374 & 0.0103327 & -0.0187097 & -0.0691313 & 1.1566371 &
0.0005370 & 0.0442957 \\
-0.0082420 & 0.0129042 & -0.0274708 & 0.0141012 & -0.0101953 &
-0.0097124 & 0.0049760 & -0.0052495 & 0.0308720 & 0.0491262 & 1.2623074
& 0.0002714 & 0.1159211 \\
0.0001788 & -0.0002519 & -0.0002161 & 0.0003628 & -0.0001373 & 0.0002337
& -0.0002736 & -0.0004421 & 0.0006609 & 0.0011171 & 1.1601008 &
0.0000001 & 0.0360424 \\
0.0308614 & -0.0149544 & 0.0398394 & 0.0067000 & -0.0450746 & -0.0441548
& 0.0428838 & 0.0512948 & -0.0480754 & 0.1173291 & 1.1892233 & 0.0015455
& 0.0769381 \\
0.0293881 & -0.0184453 & -0.0249573 & -0.0156270 & 0.0336807 & 0.0148992
& -0.0066017 & -0.0062811 & -0.0336372 & 0.0769794 & 1.1582386 &
0.0006657 & 0.0473446 \\
-0.0035175 & 0.0480690 & -0.0948735 & 0.0095865 & 0.0300692 & 0.0204187
& -0.0098307 & 0.0087946 & -0.0568538 & 0.1611849 & 1.1351555 &
0.0029078 & 0.0593438 \\
-0.0014808 & 0.0011634 & -0.0005446 & 0.0024894 & 0.0012025 & 0.0000562
& 0.0007169 & -0.0006615 & -0.0015584 & -0.0051915 & 1.1486473 &
0.0000030 & 0.0265351 \\
-0.0028768 & 0.0017630 & 0.0026588 & 0.0003358 & 0.0027506 & 0.0018773 &
-0.0018879 & 0.0018519 & -0.0038340 & -0.0079529 & 1.1952865 & 0.0000071
& 0.0645115 \\
-0.0403826 & 0.0365329 & -0.1130758 & 0.0371622 & 0.1286802 & 0.0115499
& -0.0242077 & 0.0075982 & -0.0197858 & -0.2166197 & 1.1618908 &
0.0052472 & 0.0883807 \\
0.0287452 & -0.0082435 & 0.0374486 & -0.0271778 & -0.0566585 &
-0.0268330 & 0.0055620 & 0.0637777 & -0.0232845 & 0.1045863 & 1.1637891
& 0.0012278 & 0.0580647 \\
-0.2495917 & 0.4418508 & -0.0371980 & -0.0448277 & -0.1013220 &
0.1996062 & -0.1651794 & 0.0527205 & -0.3295966 & 0.6795084 & 0.9010307
& 0.0499558 & 0.1266072 \\
-0.0433926 & 0.0123056 & 0.0355216 & -0.0067814 & 0.0277959 & -0.0028612
& -0.0176423 & 0.0288323 & 0.0255774 & -0.0933702 & 1.2364737 &
0.0009798 & 0.1032474 \\
-0.0304815 & 0.0120732 & -0.0319611 & -0.0683818 & 0.0601156 &
-0.0017343 & -0.0066589 & 0.0195699 & 0.0370247 & -0.1240267 & 1.3103089
& 0.0017287 & 0.1545785 \\
0.0270141 & -0.0375633 & 0.0303053 & -0.0289314 & -0.0153738 & 0.0040084
& -0.0057209 & -0.0049075 & 0.0169880 & -0.0592439 & 1.2238490 &
0.0003947 & 0.0898946 \\
0.0207676 & -0.0462453 & -0.0644256 & 0.0000631 & 0.2943916 & 0.1226837
& -0.0165751 & -0.0929246 & -0.2559914 & -0.4350182 & 1.1339929 &
0.0209767 & 0.1368776 \\
0.0198246 & -0.0005600 & -0.0186584 & 0.0265842 & -0.0563733 &
-0.0407399 & 0.0618222 & -0.0267152 & 0.0053448 & -0.0972523 & 1.2681421
& 0.0010631 & 0.1247225 \\
-0.0827481 & 0.1112479 & 0.0315792 & -0.0594670 & -0.0719247 & 0.0394250
& -0.0354898 & 0.0505354 & -0.0562796 & -0.2360935 & 1.0470796 &
0.0061894 & 0.0503623 \\
-0.1392216 & 0.1299171 & -0.0169533 & 0.0206706 & -0.0508455 &
-0.0602088 & 0.0397617 & 0.0184943 & 0.1090788 & -0.2026927 & 1.2860404
& 0.0046088 & 0.1524641 \\
-0.0009058 & 0.0028085 & 0.0227454 & -0.0220204 & 0.0252390 & 0.0425977
& -0.0282414 & -0.0122867 & -0.0616430 & -0.0864447 & 1.1724029 &
0.0008394 & 0.0588763 \\
-0.0500643 & 0.0882718 & -0.0370633 & -0.0714219 & -0.0857580 &
0.2775600 & -0.3307215 & 0.2834297 & -0.0971331 & 0.6484951 & 1.3591291
& 0.0466604 & 0.2736645 \\
0.0749420 & -0.1090092 & -0.0639064 & 0.1340555 & 0.0035652 & -0.0219504
& 0.0432354 & 0.0084664 & 0.0182856 & -0.2932701 & 0.9753718 & 0.0094771
& 0.0487762 \\
0.4375781 & -0.4511554 & -0.3196276 & 0.2715474 & -0.1446658 &
-0.0217175 & 0.0825145 & -0.1123090 & 0.2150019 & -0.7875551 & 0.7712849
& 0.0660138 & 0.1197120 \\
-0.0602556 & 0.0689518 & -0.1635728 & 0.0834804 & 0.1246300 & -0.0660318
& 0.0920200 & 0.0516933 & -0.0660852 & -0.2391847 & 1.1781427 &
0.0063960 & 0.1026006 \\
0.0537179 & -0.0146495 & 0.1167365 & -0.0718164 & -0.1045440 & 0.0296559
& -0.0335553 & 0.0094562 & -0.0763928 & 0.1779047 & 1.2347295 &
0.0035501 & 0.1180439 \\
-0.0247717 & 0.0022264 & -0.1495000 & 0.0901402 & 0.0373922 & -0.0368070
& 0.0508715 & -0.0262791 & 0.1082598 & -0.2120236 & 1.1222829 &
0.0050193 & 0.0690217 \\
0.0702747 & -0.0056040 & -0.0862197 & -0.0516171 & 0.0710640 &
-0.0202096 & 0.0248379 & 0.0527787 & -0.1340903 & 0.2678663 & 1.0141341
& 0.0079389 & 0.0507214 \\
0.1037700 & -0.1647361 & 0.1925935 & -0.0634693 & -0.1782590 &
-0.1394706 & 0.1131905 & -0.0213738 & 0.1807759 & -0.3791570 & 1.0358151
& 0.0158742 & 0.0871598 \\
\bottomrule
\end{longtable}

\hypertarget{tabla-de-todas-las-regresiones-posibles}{%
\subsection{Tabla de todas las regresiones
posibles:}\label{tabla-de-todas-las-regresiones-posibles}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#regresiones  \textless{}{-} ols\_step\_all\_possible(modelo)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#tabladeRegresiones \textless{}{-} as.data.frame(regresiones)}
\CommentTok{\#tabladeRegresiones \%\textgreater{}\% mutate(tabladeRegresiones, mse = regresiones$msep)}
\end{Highlighting}
\end{Shaded}


\end{document}
